name: CI

on:
  schedule:
      - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: refresh
        run: |
          bash script/smarttdns_ad.sh
          bash script/AdGuardHome_ad.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
